### ISSUE TITLE
你好,可以添加一下联系方式吗,我在修改代码的时候遇到了一点问题,想问问

### ISSUE THREAD

**Issue by YoungLee-coder** [LayFz/MoocTools#3]

**Comment by LayFz** [comment]
You can submit questions directly to the issues. I can see that it is not safe to display social information on the Internet. I am very sorry. ):

**Comment by YoungLee-coder** [comment]
确实不太安全,我有一个方法,你可以通过我的博客找到我,在我的GitHub主页有地址

**Comment by YoungLee-coder** [comment]
感谢你的reply
